plugins:
  markdownlint:
    enabled: true
    checks:
      MD002:
        enabled: false
      MD013:
        enabled: false
      MD033:
        enabled: false
  stylelint:
    enabled: true
  editorconfig:
    enabled: true
